org: org-here
app: aws-serverless-express-typescript
service: aws-serverless-express-typescript
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-stack-output
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'users-table-${sls:stage}'
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
    includeModules:
      forceExclude:
        - "@aws-sdk/client-dynamodb"
        - "@aws-sdk/lib-dynamodb"
        - "@aws-sdk/smithy-client"
        - "@aws-sdk/types"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}

package:
  individually: true

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

